# Generated by Django 5.0.2 on 2025-05-30 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('date_inc', models.DateField(auto_now_add=True)),
                ('date_mod', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialOrigem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tombo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('date_inc', models.DateField(auto_now_add=True)),
                ('date_mod', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('date_inc', models.DateField(auto_now_add=True)),
                ('date_mod', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('date_inc', models.DateField(auto_now_add=True)),
                ('date_mod', models.DateField(auto_now=True)),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.localizacao')),
                ('tombo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.materialorigem')),
            ],
        ),
        migrations.AddField(
            model_name='localizacao',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.setor'),
        ),
    ]
